"""M3C3 v2 reference runtime."""

from .audit import AuditEntry, AuditLog, verify_entries
from .constants import (
    ACTION_ALPHABET,
    AUTHORSHIP,
    DECISION_STACK_BY_REGIME,
    ENABLED_IFF,
    HIERARCHY_WEIGHTS,
    KERNEL_VERSION,
    LAYER_ORDER,
    LAYER_TYPES,
    RUNTIME_VERSION,
    SAFETY_PROPERTIES,
    WRITE_RULE,
    canonical_invariants,
)
from .engine import M3C3Runtime, TransitionResult, is_write_allowed
from .errors import (
    AuditIntegrityError,
    M3C3Error,
    RuntimeViolation,
    SchemaValidationError,
    TokenValidationError,
)
from .explore import (
    AbstractAction,
    AbstractState,
    AbstractTransition,
    ExplorationReport,
    explore_transitions,
)
from .model import (
    Action,
    ActionType,
    EvidenceState,
    HealthState,
    Layer,
    LifecycleStatus,
    M3C3State,
    MembraneLevel,
    Regime,
)
from .host_enforcement import (
    EffectClass,
    EnforcementVerdict,
    authorize_host_effect,
    effects_requiring_export,
    power_table_as_dict,
)
from .replay import ReplayResult, replay_entries, replay_file
from .validation import validate_event, validate_export, validate_state

__all__ = [
    "EffectClass",
    "EnforcementVerdict",
    "authorize_host_effect",
    "effects_requiring_export",
    "power_table_as_dict",
    "ACTION_ALPHABET",
    "AUTHORSHIP",
    "AbstractAction",
    "AbstractState",
    "AbstractTransition",
    "Action",
    "ActionType",
    "AuditEntry",
    "AuditIntegrityError",
    "AuditLog",
    "DECISION_STACK_BY_REGIME",
    "ENABLED_IFF",
    "EvidenceState",
    "ExplorationReport",
    "HIERARCHY_WEIGHTS",
    "HealthState",
    "KERNEL_VERSION",
    "LAYER_ORDER",
    "LAYER_TYPES",
    "Layer",
    "LifecycleStatus",
    "M3C3Error",
    "M3C3Runtime",
    "M3C3State",
    "MembraneLevel",
    "RUNTIME_VERSION",
    "Regime",
    "ReplayResult",
    "RuntimeViolation",
    "SAFETY_PROPERTIES",
    "SchemaValidationError",
    "TokenValidationError",
    "TransitionResult",
    "WRITE_RULE",
    "canonical_invariants",
    "explore_transitions",
    "is_write_allowed",
    "replay_entries",
    "replay_file",
    "verify_entries",
    "validate_event",
    "validate_export",
    "validate_state",
]
